// ═══════════════════════════════════════════════════════════════════
// SECTION TEMPLATES - Configuration for section types
// ═══════════════════════════════════════════════════════════════════

import type { SectionTemplate } from "@/types";

export const SECTION_TEMPLATES: SectionTemplate[] = [
  {
    type: "hero",
    label: "Hero",
    description: "Full-screen hero with headline and CTA",
    icon: "◆",
    defaultConfig: {},
    defaultMinHeight: "100vh",
    isTemplate: true,
  },
  {
    type: "problem",
    label: "Problem",
    description: "Two-column manifesto layout",
    icon: "◇",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "quote",
    label: "Quote",
    description: "Centered quote with background",
    icon: "❝",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "shift",
    label: "Shift",
    description: "Three-card feature section",
    icon: "△",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "proof",
    label: "Proof",
    description: "Logo bar / social proof",
    icon: "★",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "tagline",
    label: "Tagline",
    description: "Simple centered tagline",
    icon: "—",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "services",
    label: "Services",
    description: "Service cards grid",
    icon: "▤",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "about",
    label: "About",
    description: "Bio with portrait",
    icon: "○",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "musings",
    label: "Musings",
    description: "Blog posts grid",
    icon: "✎",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "cta",
    label: "CTA",
    description: "Call-to-action section",
    icon: "→",
    defaultConfig: {},
    defaultMinHeight: "auto",
    isTemplate: true,
  },
  {
    type: "freeform",
    label: "Freeform",
    description: "Blank canvas for custom layouts",
    icon: "☐",
    defaultConfig: {},
    defaultMinHeight: "50vh",
    isTemplate: false,
  },
];
