"""Port the Prompt to Loop breakdown into the AP lecture: assets to public/,
each chapter's head into arc-head data, its body verbatim, the CSS scoped
under .ptl with the palette remapped to Thoughtform tokens."""
import base64
import html
import io
import json
import os
import re

SRC = r"C:\Users\buyss\Downloads\prompt-to-loop\index.html"
REPO = r"C:\Users\buyss\Manifold Delta\Artifacts\01_thoughtform"
PUB_DIR = os.path.join(REPO, "public", "arcs", "ap-hogeschool", "prompt-to-loop")
PUB_URL = "/arcs/ap-hogeschool/prompt-to-loop"
ROUTE = os.path.join(REPO, "app", "(marketing)", "arcs", "ap-hogeschool")

s = io.open(SRC, encoding="utf-8").read()
os.makedirs(PUB_DIR, exist_ok=True)

# ── 1. assets ────────────────────────────────────────────────────────────
EXT = {"video/mp4": "mp4", "image/jpeg": "jpg", "image/png": "png"}
counter = {"n": 0}


def save(m):
    mime, b64 = m.group(1), m.group(2)
    counter["n"] += 1
    name = "loop.mp4" if mime == "video/mp4" else f"ptl-{counter['n']:02d}.{EXT[mime]}"
    with open(os.path.join(PUB_DIR, name), "wb") as f:
        f.write(base64.b64decode(b64))
    return f"{PUB_URL}/{name}"


s = re.sub(r"data:([a-z]+/[a-z0-9.+-]+);base64,([A-Za-z0-9+/=]+)", save, s)
print("assets:", counter["n"], sorted(os.listdir(PUB_DIR)))

# ── 2. slides ────────────────────────────────────────────────────────────
IDS = ["top", "setup", "runs", "ask", "look", "idea", "plan", "stuff", "make",
       "sound", "check", "cost", "next", "hero", "snd"]


def reid(h):
    for i in IDS:
        h = h.replace(f'id="{i}"', f'id="ptl-{i}"').replace(f'href="#{i}"', f'href="#ptl-{i}"')
    return h


def reclass(h):
    """Every class in the breakdown gets a `ptl-` prefix: the page around it
    already owns `.station`, `.plate`, `.hero`, `.title`, `.k` and others, and
    those rules reached into the slides (ADR-141 U3)."""
    def one(m):
        toks = [t if t.startswith("ptl-") else f"ptl-{t}" for t in m.group(1).split()]
        return f'class="{" ".join(toks)}"'
    return re.sub(r'class="([^"]+)"', one, h)


def text(h):
    return html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", h))).strip()


def kick(h):
    m = re.match(r"\s*<b>(\d+)</b>(.*)", h, flags=re.S)
    return f"{m.group(1)} · {text(m.group(2))}" if m else text(h)


slides = []
for m in re.finditer(r'<section class="sec[^"]*" id="(\w+)"[^>]*>(.*?)</section>', s, flags=re.S):
    sid, inner = m.group(1), m.group(2)
    tm = re.search(r'<h[12] class="title"><span>(.*?)</span><span class="a">(.*?)</span></h[12]>', inner, flags=re.S)
    km = re.search(r'<span class="kick">(.*?)</span>', inner, flags=re.S)
    sm = re.search(r'<p class="sub">(.*?)</p>', inner, flags=re.S)
    if sid == "top":
        steps = re.search(r'<ol class="steps">.*?</ol>', inner, flags=re.S).group(0)
        film = inner[inner.index('<div class="phone">'):]
        film = film[: film.index('<div class="hero__meta">')]
        meta = re.search(r'<div class="hero__meta">.*?</div>', inner, flags=re.S).group(0)
        body = (f'<div class="ptl-herobody"><div class="ptl-herobody__film">{film}{meta}</div>'
                f"{steps}</div>")
    else:
        head_end = inner.index("</p>", sm.start()) + 4
        rest = inner[head_end:]
        rest = rest[rest.index("</div>") + 6:]  # close .head
        rest = rest.strip()
        assert rest.endswith("</div>"), sid
        body = rest[: -len("</div>")].strip()  # close .wrap
    slides.append({
        "id": f"ptl-{sid}",
        "eyebrow": kick(km.group(1)) if sid != "top" else text(km.group(1)),
        "pre": text(tm.group(1)),
        "em": text(tm.group(2)),
        "sub": text(sm.group(1)),
        "band": 'data-tone="band"' in s[m.start(): m.start() + 200],
        "body": reclass(reid(re.sub(r"\s+", " ", body))),
    })
print("slides:", [x["id"] for x in slides])

ts = """/* GENERATED by scripts/arcs/port-prompt-to-loop.py from the owner's
   breakdown (Downloads/prompt-to-loop/index.html, 2026-10-02). The heads
   become arc heads; every body is the breakdown's own markup, verbatim, with
   its ids prefixed `ptl-` and its media moved to public/. Re-run the script
   rather than hand-editing the bodies. */

export interface PromptToLoopSlide {
  id: string;
  eyebrow: string;
  pre: string;
  em: string;
  sub: string;
  body: string;
}

export const PROMPT_TO_LOOP_SLIDES: readonly PromptToLoopSlide[] = """
ts += json.dumps(
    [{k: v for k, v in x.items() if k != "band"} for x in slides], ensure_ascii=False, indent=2
) + ";\n"
io.open(os.path.join(ROUTE, "promptToLoopSlides.ts"), "w", encoding="utf-8", newline="\n").write(ts)

# ── 3. css ───────────────────────────────────────────────────────────────
css = re.findall(r"<style[^>]*>(.*?)</style>", s, flags=re.S)[0]
css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)

DROP = re.compile(r"^(:root|html|body|\*$|\.bar|\.nav|\.wrap|\.sec|\.head|\.kick|\.title|\.sub$|\.hero(\s|$|,))")


def split_top(sel):
    out, depth, buf = [], 0, ""
    for ch in sel:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(buf.strip()); buf = ""
        else:
            buf += ch
    out.append(buf.strip())
    return [x for x in out if x]


def scope(sel):
    keep = []
    for one in split_top(sel):
        if DROP.match(one):
            continue
        if one == "*":
            keep.append(".ptl *"); continue
        one = re.sub(r"\.(?!ptl-)([A-Za-z][\w-]*)", lambda m: f".ptl-{m.group(1)}", one)
        keep.append(f".ptl {one}")
    return ", ".join(keep)


def walk(block):
    out, i = [], 0
    while i < len(block):
        j = block.find("{", i)
        if j < 0:
            break
        head = block[i:j].strip()
        depth, k = 1, j + 1
        while depth:
            depth += {"{": 1, "}": -1}.get(block[k], 0); k += 1
        inner = block[j + 1: k - 1]
        i = k
        if head.startswith("@media") or head.startswith("@supports"):
            if "prefers-color-scheme" in head:
                continue
            sub = walk(inner)
            if sub.strip():
                out.append(f"{head} {{\n{sub}}}\n")
        elif head.startswith("@"):
            out.append(f"{head} {{{inner}}}\n")
        else:
            sel = scope(head)
            if sel:
                out.append(f"{sel} {{{inner.strip()}}}\n")
    return "".join(out)


scoped = walk(css)
TOKENS = """/* The Prompt to Loop breakdown, ported into the AP lecture (ADR-141 U3).
   GENERATED by scripts/arcs/port-prompt-to-loop.py: every rule below the
   token block is the breakdown's own, scoped under `.ptl`. Its palette is
   remapped onto Thoughtform's: the ink ramp and edges are the arcs' own
   (`.arc-root` re-derives them for light, so this block needs no theme
   branch), gold is the accent, the green is the human's, corners are square
   and nothing casts a shadow. The scene colours (`--sc-*`) are the video's
   own palette and stay, as the breakdown says, only where the picture is
   about the video. */
.ptl {
  --bg: transparent;
  --band: rgba(var(--dawn-rgb), 0.03);
  --card: var(--arc-plate);
  --fg: var(--arc-ink);
  --muted: var(--arc-ink-70);
  --faint: var(--arc-ink-50);
  --hair: var(--arc-edge);
  --hair-2: rgba(var(--dawn-rgb), 0.2);
  --accent: var(--gold);
  --accent-ink: var(--gold-ink);
  --accent-soft: var(--arc-gold-wash);
  --on-accent: var(--gold-contrast);
  --obj: var(--gold);
  --on-obj: var(--gold-contrast);
  --on-obj-muted: rgba(10, 9, 8, 0.7);
  --live: var(--atreides-ink, #7a9e6a);
  --live-soft: rgba(var(--atreides-rgb, 122, 158, 106), 0.16);
  --miss: #c8644f;
  --miss-soft: rgba(200, 100, 79, 0.14);
  --shadow: none;
  --shadow-pop: none;
  --sc-black: #26232a;
  --sc-orange: #f06a22;
  --sc-violet: #4b3d63;
  --sc-gold: #d9b45a;
  --sc-cream: #efe3c8;
  --sans: var(--font-pp-neue-montreal, system-ui, sans-serif);
  --mono: var(--font-pt-mono, "PT Mono", ui-monospace, monospace);
  --r-plate: 0;
  --r-ctl: 0;
  --bar: 0px;
  font-family: var(--sans);
  font-size: 15px;
  line-height: 1.45;
  color: var(--fg);
}
/* No rounded corners, anywhere in the breakdown (owner, 2026-10-02). */
.ptl *,
.ptl *::before,
.ptl *::after {
  box-sizing: border-box;
  border-radius: 0 !important;
}
.ptl rect {
  rx: 0;
  ry: 0;
}
"""
HERO = """
/* The slides take the ITP wall's tighter beat: less section padding, a
   shorter gap under the head, so a picture-heavy chapter sits on one screen. */
.arc-root .ptl-sec {
  --arc-sec-pad: clamp(28px, 4vh, 72px);
}
.arc-root .ptl-sec .arc-head {
  margin-bottom: clamp(16px, 3vh, 44px);
}
/* The opening slide's body: the finished loop beside the twelve chapters. */
.ptl .ptl-herobody {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: clamp(28px, 4vw, 72px);
}
.ptl .ptl-herobody__film {
  flex: 0 0 auto;
  width: min(300px, calc((100svh - 420px) * 9 / 16));
}
.ptl .ptl-herobody .ptl-phone {
  max-width: none;
}
.ptl .ptl-herobody .ptl-steps {
  max-width: 520px;
  margin: 0;
}
@media (max-width: 1000px) {
  .ptl .ptl-herobody {
    flex-direction: column;
  }
  .ptl .ptl-herobody__film {
    width: min(260px, 70vw);
  }
}
"""
io.open(os.path.join(ROUTE, "prompt-to-loop.css"), "w", encoding="utf-8", newline="\n").write(
    TOKENS + "\n" + scoped + HERO
)
print("css bytes:", len(TOKENS) + len(scoped) + len(HERO))
